import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import "./globals.css";
import { Alexandria } from "next/font/google";

const alexandria = Alexandria({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Home Page | PPI Bartin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={alexandria.variable}>
      <body className="cursor-default">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
