import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import "./globals.css";
import { Open_Sans, Merriweather } from "next/font/google";
import { Toaster } from "sonner";

const opensans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-opensans",
});

const merriweather = Merriweather({
  subsets: ["latin"],
  variable: "--font-merriweather",
});

export const metadata: Metadata = {
  title: "Home Page | PPI Bartin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${opensans.variable} ${merriweather.variable}`}>
      <body className="cursor-default font-body">
        <Toaster />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
